### ISSUE TITLE
Get validation methods for CA or Product

### ISSUE THREAD

**Issue by Jaykju** [psw-group/api-v1#11]
As far as I can see currently there is no way to get available validation methods of a product or CA before placing an order. 

Since we want to automate the process as far as possible we would like to use cname or dnstxt validation in most cases. 

Currently the only way would be to:
1. Place an order using email validation (this is available for all CAs).
2. Get the order item(s) to be able to access the certificate(s).
3. Get the possible validation methods of the certificate(s).
4. Create a job to change the validation method of the certificate.
5. Wait until this is finished.
6. Get the validation details for a certificate.

I think this process could be simplified if one was able to get the possible validation methods beforehand, exactly as ordering through the PSW-console (this seems to use another API with an /approve endpoint that does exactly this) does this.

**Comment by binsoul** [comment]
There ist a new endpoint `/v1/products/{id}/validation-methods` available now which returns the data you need. It's integrated in the test environment for now and will be integrated into the production environment next week.
