### ISSUE TITLE
getState() must be of the type string, null returned

### ISSUE THREAD

**Issue by marcriemer** [psw-group/api-v1#14]
getState() of the Job resource class returns NULL on certificate renew.

Type error: Return value of PswGroup\Api\Model\Resource\Job::getState() must be of the type string, null returned

Should the return value not be a state object like all getState() methods?

**Comment by binsoul** [comment]
The endpoint returned the wrong resource. This is fixed now.

The state of the job could be another resource but we decided to make it an enum with the values ```submitted```, ```running```, ```succeeded``` and ```failed``` because there will probably never be another state besides those values.
