### ISSUE TITLE
Question: Isn't #Order/orderContact redundant?

### ISSUE THREAD

**Issue by dmke** [psw-group/api-v1#4]
I was wondering what purpose the `orderContact` fulfills.

As per [`docs.jsonld`](https://test-api-v1.psw-group.de/v1/docs.jsonld), "this contact receives all order related information including prices".

For us as resellers, this information should rarely, if ever, change. It is the same information as present in the PSW Console (https://test-console.psw-group.de/account), which makes the field in the Order redundant.

Can you elaborate as to why this field is required?

**Comment by binsoul** [comment]
Yes this field is not useful if you only have one contact that never changes. But we do have 2 use cases for it. The first one is a company with multiple departments which use the same client to order certificates. And the second one is a company which orders certificates on behalf of their customers and they become customers of PSW this way.

To make it easier for your use case you can use an existing contact from https://test-console.psw-group.de/contacts for every order. The `orderContact` field has a property `contact` where you can supply an IRI like `/v1/contacts/AC023901` or the number `AC023901` of a contact from your account.

**Comment by dmke** [comment]
Ah, I see. Thank you.
