### ISSUE TITLE
Bug: Job state does not change

### ISSUE THREAD

**Issue by dmke** [psw-group/api-v1#6]
### Problem

I've issued a `/v1/jobs/orders/cancel` and got the following response:

```json
{
  "@context": "/v1/contexts/Job",
  "@id": "/v1/jobs/66",
  "@type": "Job",
  "id": 66,
  "state": "submitted",
  "name": "Cancel order BS20000169",
  "createdAt": "2020-06-24T12:11:40+02:00",
  "startedAt": null,
  "stoppedAt": null
}
```

(This is on the test system).

The order's state then very quickly changed to "cancelled". I've also received a order cancellation confirmation email.

The job's state however did not change. Now, an hour later, I still receive the same response (state = submitted, started/stopped timestamp = null).

We need to keep track of jobs (not only order cancellations, also reissuing/revoking certificates, change validation, etc.).

### Proposed solution

Update the state and timestamps after executing a job.

In the long term, a webhook (#1) would be useful to have for job state changes (to eliminate polling).

### Workaround

In case of `/v1/jobs/orders/cancel`, we could instead poll the order instead, and do something similar for other jobs as well. However, it is not 100% clear where the effect of `/v1/jobs/certificates/change-validation` could be observed (neither `/v1/orders/{id}`, nor `/v1/orders/{id}/items` contain this information bit).

**Comment by binsoul** [comment]
The job state is updated now including the start and stop times.
