### ISSUE TITLE
Which {id} is ment ?

### ISSUE THREAD

**Issue by maxclients** [psw-group/api-v1#9]
When using the  [number] => BS20.... of an order in other requests this number can't be found e.g. in " /v1/certificates/{id}/validation-data ". How can I get the "{id}" ?
I need to get the hash values for http validation

**Comment by binsoul** [comment]
Each order results in one or more certificates. To get a list of all items of an order use the item endpoint, e.g. `/v1/orders/BS20000123/items`. Each order item, which is associated with a certificate, will have a property called `certificate`. Use the number of this certificate to retrieve the validation data, e.g. `/v1/certificates/C20000234/validation-data`.

Please keep in mind that the validation data is only available if the order has the state `processing` or the certificate has the state `validating`. If one of them has the states `new` or `incomplete` PSW is propbably still working on the prevalidation of your certificate.
